### ISSUE TITLE
Feature Request: Single Subscription for Small-Enterprise model

### ISSUE THREAD

**Issue by richardf5** [Azure/Azure-Landing-Zones#2519]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

Yes. 

**Describe the solution you'd like**

We have many customers who want the 'small enterprise' model whereby the Management, Connectivity and Identity subscription are all in one. This includes our small/mid-market customers.

Their I.T. is simply not that distributed or separated enough to warrant splitting this function up into three separate Subscriptions.

This is currently possible when using the Azure Landing Zone Accelerator Wizard. Under 'Azure Core Setup' you can select either 'Dedicated (recommended)' or 'Single'.

Please see here for more information: https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md

**Additional context**
I've tried to find a decent way to do this with the Enterprise Scale Terraform Module. Hoping you have better insight and skills :-)

**Comment by capitanou** [comment]
@jaredfholgate 

Is this still possible to use a single subscription?

I tried it with the following in my inputs.yaml for the bootstrap.  Basically I specified the same subscription for all.

subscription_ids:
  management: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
  identity: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
  connectivity: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
  security: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"

When I try to apply the plan from the pipeline the bootstrap deployed I receive the following errors: 

Error: Invalid value for variable
│ 
│   on main.management.groups.tf line 14, in module "management_groups":
│   14:   subscription_placement                                           = module.config.outputs.management_group_settings.subscription_placement
│     ├────────────────
│     │ var.subscription_placement is map of object with 4 elements
│ 

==Each subscription ID can only be specified once in the==
==subscription_placement variable.==
│ 
│ This was checked by the validation rule at
│ .terraform/modules/management_groups/variables.tf:636,3-13.
╵
Is there a way to fix this and ensure a single subscription deployment?

**Comment by kitforbes** [comment]
I've encountered the same issue as you, @capitanou. I'm going to start digging through the Accelerator's logic to try and understand where it went wrong. Have you identified the problem since last week?
